### PR TITLE
Force rustfmt

### PR DESCRIPTION
**Pull request by khssnv**
* Rustfmt on save for VS Code
* Rustfmt on pre-commit
* Rustfmt on push in CI before build

Also, the existing code base was updated by `cargo +nightly fmt`.

### CODE REVIEW

**Comment by MRamanenkau** [comment]
> * Rustfmt on save for VS Code
> * Rustfmt on pre-commit
> * Rustfmt on push in CV before build
> 
> Also, the existing code base was updated by `cargo +nightly fmt`.

Am I right to trigger the second case we need to run `init.sh`? 
I'm asking because this script is used by CI and the developers usually don't use it. This means that the second case won't be used as it was desired and in CI will have identical checks

**Comment by khssnv** [comment]
> Am I right to trigger the second case we need to run `init.sh`? I'm asking because this script is used by CI and the developers usually don't use it. This means that the second case won't be used as it was desired and in CI will have identical checks

Yes, I put the pre-commit hook setup line at the end of `init.sh`. It does not alter the jobs in CI, but works for local environment initialization. I had to do that because git does not allow implicit hooks setup and we should introduce some hooks setup procedure anyway. Another option could be a `Development` section in the `README.md` that holds the hook setup. Which way do you prefer (or any other option)?

**Comment by MRamanenkau** [comment]
> > Am I right to trigger the second case we need to run `init.sh`? I'm asking because this script is used by CI and the developers usually don't use it. This means that the second case won't be used as it was desired and in CI will have identical checks
> 
> Yes, I put the pre-commit hook setup line at the end of `init.sh`. It does not alter the jobs in CI, but works for local environment initialization. I had to do that because git does not allow implicit hooks setup and we should introduce some hooks setup procedure anyway. Another option could be a `Development` section in the `README.md` that holds the hook setup. Which way do you prefer (or any other option)?

What do you mean by "git does not allow implicit hooks setup and we should introduce some hooks setup procedure anyway"?

According to [Git documentation](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) we need to
1. Create a file with the hook:
`
#!/bin/sh

# Run `cargo +nightly fmt` before committing

# Stash any unstaged changes
git stash -q --keep-index

# Run `cargo +nightly fmt` and capture the exit code
cargo +nightly fmt -- --check
FMT_RESULT=$?

# Restore the stashed changes
git stash pop -q

# Exit with the result of `cargo +nightly fmt`
exit $FMT_RESULT
`
2. Run `chmod +x .git/hooks/pre-commit` to make the file executable

**Comment by khssnv** [comment]
> What do you mean by "git does not allow implicit hooks setup and we should introduce some hooks setup procedure anyway"?

I mean I can't publish `.git/hooks/pre-commit` to eliminate the hook setup.

**Review by MRamanenkau — APPROVED** [review]

**Pull request merged**
