### PR TITLE
Add `pallet-ddc-staking` to the `cere` runtime

### PR DESCRIPTION
**Pull request by khssnv**

### CODE REVIEW

**Review by rakanalh — COMMENTED** [review]
Can this be merged immediately or does it need to wait until we reach a specific substrate version?

**Comment by yahortsaryk** [comment]
> Can this be merged immediately or does it need to wait until we reach a specific substrate version?

It is better to close this as we will need to re-configure the `cere` runtime

**Comment by aie0** [comment]
needs to wait for https://github.com/Cerebellum-Network/blockchain-node/pull/159

**Comment by rakanalh** [comment]
@aie0 #159 is merged. Do we still need this PR?

**Comment by yahortsaryk** [comment]
@rakanalh, @aie0 guys, it is better to close this PR as its reason is to deliver the Staking Pallet to the Blockchain Testnet environment. 
We need to update the Blockchain Testnet not only with the Staking Pallet, but also with Nodes, Clusters, Customers, and Payouts Pallets in order to launch the production. It will be easier to add all these pallets for the `cere` runtime in 1 single PR.
A lot of things have changed since this PR was opened

**Comment by yahortsaryk** [comment]
Closed due to [#189](https://github.com/Cerebellum-Network/blockchain-node/pull/189)

**Pull request closed without merging**
